[workspace]
authors = ["Haven Madray <sgpublic2002@gmail.com>"]
channels = ["conda-forge"]
name = "LEDataset"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
create = {cmd = ["python", "./scripts/dataset_creator.py"]}
create_for_contest = {cmd = ["python", "./scripts/dataset_creator.py", "--for-contest"]}
create_for_test = {cmd = ["python", "./scripts/dataset_creator.py", "--for-contest", "--for-test"]}
rename_action = {cmd = ["python", "./scripts/dataset_renamer.py"]}
rename_restore = {cmd = ["python", "./scripts/dataset_renamer.py", "--restore"]}
check_imgs = {cmd = ["python", "./scripts/check_imgs.py"]}

huggingface_login = {cmd = ["huggingface-cli", "login"]}
huggingface_whoami = {cmd = ["huggingface-cli", "whoami"]}
huggingface_logout = {cmd = ["huggingface-cli", "logout"]}
sample_dataset_loader = {cmd = ["python", "./sample_dataset_loader.py"]}

[dependencies]
python = ">=3.13,<3.14"
pixi-pycharm = ">=0.0.10,<0.0.11"
ty = ">=0.0.11,<0.0.12"

[pypi-dependencies]
pathlib = ">=1.0.1, <2"
pandas = ">=2.3.3, <3"
pandas-stubs = ">=2.3.3.251201, <3"
pyarrow = ">=22.0.0, <23"
huggingface-hub = ">=0.33.4,<0.34"
datasets = {extras = ["vision"], version = ">=4.0.0,<4.1"}
pillow = ">=12.1.0, <13"

